[package]
name = "dmx"
version = "0.1.0"
authors = ["Til Blechschmidt <til@blechschmidt.de>"]
links = "interface"
build = "build.rs"

[[bin]]
name = "frontend"
path = "src/frontend/main.rs"

[[bin]]
name = "backend"
path = "src/backend/main.rs"

[lib]
name = "structures"
path = "src/structs/structs.rs"

[features] #TODO: Make this automagically and send it to the interface
default = []
fake_if = []

[dependencies]
conrod = "0.32.0"
daggy = "0.4.0"
piston = "0.17.0"
piston_window = "0.37.0"
pistoncore-input = "0.8.0"
piston2d-graphics = "0.15.0"
find_folder = "0.3.0"
num = "0.1.30"
rand = "0.3.13"
time = "0.1.34"
meval = { git = "https://github.com/rekka/meval-rs" }
#vecmath = "0.2.0"

[build-dependencies]
gcc = "0.3"
